# Generated by Django 6.1.1 on 2026-10-01 15:48

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_publicar_ofertas', models.BooleanField(default=False)),
                ('canais_automaticos', models.JSONField(blank=True, default=list)),
                ('cache_retencao_hours', models.PositiveIntegerField(default=120)),
                ('campanha_sazonal', models.CharField(blank=True, default='NENHUM', max_length=80)),
                ('turno_padrao', models.CharField(blank=True, default='', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_automacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(db_index=True, default='INICIANDO', max_length=40)),
                ('produtos_processados', models.PositiveIntegerField(default=0)),
                ('produtos_total', models.PositiveIntegerField(default=0)),
                ('links_obtidos', models.PositiveIntegerField(default=0)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('keywords_loop', models.JSONField(blank=True, default=list)),
                ('categorias_loop', models.JSONField(blank=True, default=list)),
                ('erro', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execucao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('OK', 'OK'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('mensagem', models.CharField(max_length=2000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.execucao')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=80)),
                ('estado', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=80)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_local', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, default='MAGALU', max_length=40)),
                ('categoria', models.CharField(db_index=True, max_length=120)),
                ('nome', models.CharField(blank=True, default='', max_length=500)),
                ('url_produto', models.URLField(max_length=2000)),
                ('preco_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imagem_url', models.URLField(blank=True, default='', max_length=3000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTA', 'Pronta'), ('ENVIADA', 'Enviada'), ('ARQUIVADA', 'Arquivada')], default='RASCUNHO', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.produto')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('conteudo', models.TextField(blank=True, default='')),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('preco_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagem', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.produto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='core.produto')),
            ],
            options={
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_afiliado', models.URLField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(db_index=True, default='REVISAR', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afiliado', to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoQuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_quentes', to=settings.AUTH_USER_MODEL)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_quente', to='core.produto')),
            ],
            options={
                'ordering': ['-score', '-calculado_em'],
            },
        ),
        migrations.CreateModel(
            name='TemplateOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CATEGORIA', 'Categoria'), ('KEYWORD', 'Palavra-chave')], max_length=20)),
                ('chave', models.CharField(max_length=160)),
                ('chamadas', models.JSONField(blank=True, default=list)),
                ('divulgar_sem_template', models.BooleanField(default=False)),
                ('nativo', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_oferta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'chave'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100)),
                ('canal', models.CharField(blank=True, default='', max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Alerta'), ('ERROR', 'Erro')], default='WARNING', max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('mensagem', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'codigo'), name='uniq_alerta_ativo_codigo_owner')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('ativo', models.BooleanField(default=False)),
                ('destino', models.CharField(blank=True, default='', max_length=255)),
                ('token', core.fields.EncryptedTextField(blank=True, default='')),
                ('endpoint', models.URLField(blank=True, default='', max_length=1000)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracaocanal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'canal'), name='uniq_canal_por_owner')],
            },
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('owner', 'url_produto'), name='uniq_produto_por_owner_url'),
        ),
        migrations.AddConstraint(
            model_name='templateoferta',
            constraint=models.UniqueConstraint(fields=('owner', 'tipo', 'chave'), name='uniq_template_por_owner_tipo_chave'),
        ),
    ]
